version: '3.7'

services:
  metabase:
    image: metabase/metabase:v0.46.2
    restart: always
    ports:
      - 3001:3000
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: bunnygood
      MB_DB_HOST: timescaledb
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"
        max-size: "10m"
        max-file: "3"
    networks:
      - bunny-net

volumes:
  metabase-data:


networks:
  bunny-net:
    external: true
