from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule

from bunny_good.services.prefect_agent import cmoney, sino, twse

deployments = [
    Deployment.build_from_flow(
        flow=cmoney.flow_daily_price,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="0 19 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_daily_price_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_daily_price_index_etf_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_invest,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="2 19 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_foreign,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="4 19 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_foreign_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_dealer,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="6 19 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_dealer_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_fund,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="8 19 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_institute_fund_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    # 00:00:00
    Deployment.build_from_flow(
        flow=cmoney.flow_dividend_policy,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="0 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_dividend_policy_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_dividend_policy_quarterly,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="2 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_dividend_policy_quarterly_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_margin_short,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="4 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_margin_short_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_holidays,
        name="cmoney",
        version=1,
        schedule=(CronSchedule(cron="6 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=cmoney.flow_holidays_history,
        name="cmoney",
        version=1,
        is_schedule_active=False,
        tags=["twse", "cmoney"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    # sino
    Deployment.build_from_flow(
        flow=sino.flow_contracts,
        name="sino",
        version=1,
        schedule=(CronSchedule(cron="5 8 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "sino"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=sino.flow_contracts,
        name="sino-2",
        version=1,
        schedule=(CronSchedule(cron="20 8 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "sino"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    Deployment.build_from_flow(
        flow=sino.flow_kbars,
        name="kbars",
        version=1,
        schedule=(CronSchedule(cron="0 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse", "sino"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
    # twse
    Deployment.build_from_flow(
        flow=twse.flow_stock_info,
        name="stock_info",
        version=1,
        schedule=(CronSchedule(cron="19 0 * * *", timezone="Asia/Taipei")),
        is_schedule_active=True,
        tags=["twse"],
        infra_overrides={"env": {}},
        work_pool_name="local-work",
    ),
]
if __name__ == "__main__":
    for deployment in deployments:
        deployment.apply()
