version: "3.7"

x-redash-service:
  # image: redash/redash:10.1.0.b50633
  &redash-service
  build:
    context: .
    args:
      skip_frontend_build: "true" # set to empty string to build
  image: redash:latest
  volumes:
    - .:/app
  env_file:
    - .env
  networks:
    - bunny-net

x-redash-environment:
  &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://:bunnygood@redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  # REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  # REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  # Set secret keys in the .env file

services:
  server:
    <<: *redash-service
    command: dev_server
    ports:
      - "5001:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    environment:
      <<: *redash-environment
  worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  # email:
  #   image: maildev/maildev
  #   ports:
  #     - "1080:80"
  #   restart: unless-stopped

networks:
  bunny-net:
    external: true
