version: '3'

services:
  redis:
    image: redis:7.0.11
    container_name: redis
    command: redis-server --save "" --appendonly no --requirepass bunnygood
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - bunny-net

volumes:
  redis-data:


networks:
  bunny-net:
    external: true
